### ISSUE TITLE
Missing configuration for GIRDER_API_URL on gwvolman

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/deploy-dev#10]
The current dev branch yields three similar stack traces in the `celery_worker` logs when launching a Tale with the default configuration:
```
[2018-12-20 19:45:11,121: INFO/ForkPoolWorker-2] Calling: girderfs -c wt_work --api-url https://girder.dev.wholetale.org/api/v1 --api-key <REDACTED> /var/lib/docker/volumes/5c1be93ebb2d3300015a150b_lambert8_uNusFW/_data/workspace 5c1be93ebb2d3300015a150b
Traceback (most recent call last):
  File "/usr/local/bin/girderfs", line 11, in <module>
    load_entry_point('girderfs==0.5.0rc1', 'console_scripts', 'girderfs')()
  File "/usr/local/lib/python3.5/dist-packages/girderfs/__main__.py", line 47, in main
    gc.authenticate(apiKey=args.api_key)
  File "/usr/local/lib/python3.5/dist-packages/girder_client/__init__.py", line 331, in authenticate
    'key': apiKey
  File "/usr/local/lib/python3.5/dist-packages/girder_client/__init__.py", line 511, in post
    data=data, json=json, headers=headers, jsonResp=jsonResp)
  File "/usr/local/lib/python3.5/dist-packages/girder_client/__init__.py", line 497, in sendRestRequest
    response=result)
girder_client.HttpError: HTTP error 400: POST https://girder.dev.wholetale.org/api/v1/api_key/token?key=<REDACTED>
Response text: {"message": "Invalid API key.", "type": "validation"}
```

I believe this is because it is attempting to send to `girder.dev.wholetale.org`, even when `DOMAIN` is defaulted to `girder.local.wholetale.org`. The Instance still starts up, so it is unclear whether or not this is causing an actual problem during runtime...

Digging into it, `GIRDER_API_URL` is either picked up or defaulted [here in gwvolman](https://github.com/whole-tale/gwvolman/blob/master/gwvolman/constants.py#L15-L19). `GIRDER_API_URL` is [not explicitly specified in run-worker.sh](https://github.com/whole-tale/deploy-dev/blob/dev/run_worker.sh#L15-L36), so I am assuming that default value is being used. This incorrect value is then [sent as part of the command](https://github.com/whole-tale/gwvolman/blob/master/gwvolman/tasks.py#L120-L124).

**Comment by craig-willis** [comment]
We set `GIRDER_API_URL` in the Terraform deployment: https://github.com/whole-tale/terraform_deployment/blob/master/scripts/start-worker.sh#L20

I think we just need to add:
```
-e GIRDER_API_URL=https://girder.${domain}/api/v1 
```

**Comment by Xarthisius** [comment]
I "fixed" that without thinking, because I forgot it's actually handled elsewhere. TL;DR for local deployment that variable is **not set** on purpose. 

Long story: Due to the combination of using DNS entry pointing to 127.0.0.1 and doing ns change, API_URL needs to be set to an internal ip that girder container is using. It's handled here:

https://github.com/whole-tale/gwvolman/blob/master/gwvolman/constants.py#L15-L19

My guess is that `socket` was failing to get that hostname for some reason, but I can't reproduce that on neither my laptop, nor nebula VM. @bodom0015 could you try exec'ing into `celery_worker` and running:

```
python -c 'import socket; socket.gethostbyname("girder")'
```
